### ISSUE TITLE
Can't create simple identity

### ISSUE THREAD

**Issue by cypripedium128** [radixdlt/radixdlt-js#119]
```
radixUniverse.bootstrap(RadixUniverse.LOCAL_SINGLE_NODE)
const identityManager = new RadixIdentityManager()
const myIdentity = identityManager.generateSimpleIdentity()
```

causes the following error:

```
/var/www/radixdlt-js-server-example/node_modules/radixdlt/build/main/modules/account/RadixTransferAccountSystem.js:46
        this.balance[RadixTokenManager_1.radixTokenManager.nativeToken.toString()] = new bn_js_1.default(0);
                                                                       ^

TypeError: Cannot read property 'toString' of undefined
    at new RadixTransferAccountSystem (/var/www/radixdlt-js-server-example/node_modules/radixdlt/build/main/modules/account/RadixTransferAccountSystem.js:46:72)
    at new RadixAccount (/var/www/radixdlt-js-server-example/node_modules/radixdlt/build/main/modules/account/RadixAccount.js:102:35)/var/www/radixdlt-js-server-example/node_modules/radixdlt/build/main/modules/account/RadixTransferAccountSystem.js:46
        this.balance[RadixTokenManager_1.radixTokenManager.nativeToken.toString()] = new bn_js_1.default(0);
                                                                       ^

TypeError: Cannot read property 'toString' of undefined
    at new RadixTransferAccountSystem (/var/www/radixdlt-js-server-example/node_modules/radixdlt/build/main/modules/account/RadixTransferAccountSystem.js:46:72)
    at new RadixAccount (/var/www/radixdlt-js-server-example/node_modules/radixdlt/build/main/modules/account/RadixAccount.js:102:35)
    at RadixSimpleIdentity.RadixIdentity (/var/www/radixdlt-js-server-example/node_modules/radixdlt/build/main/modules/identity/RadixIdentity.js:29:24)
    at new RadixSimpleIdentity (/var/www/radixdlt-js-server-example/node_modules/radixdlt/build/main/modules/identity/RadixSimpleIdentity.js:31:28)
    at RadixIdentityManager.generateSimpleIdentity (/var/www/radixdlt-js-server-example/node_modules/radixdlt/build/main/modules/identity/RadixIdentityManager.js:41:24)
    at Object.<anonymous> (/var/www/radixdlt-js-server-example/src/server.js:10:36)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at RadixSimpleIdentity.RadixIdentity (/var/www/radixdlt-js-server-example/node_modules/radixdlt/build/main/modules/identity/RadixIdentity.js:29:24)
    at new RadixSimpleIdentity (/var/www/radixdlt-js-server-example/node_modules/radixdlt/build/main/modules/identity/RadixSimpleIdentity.js:31:28)
    at RadixIdentityManager.generateSimpleIdentity (/var/www/radixdlt-js-server-example/node_modules/radixdlt/build/main/modules/identity/RadixIdentityManager.js:41:24)
    at Object.<anonymous> (/var/www/radixdlt-js-server-example/src/server.js:10:36)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
```

**Comment by cypripedium128** [comment]
I now realized that i have to use `radixUniverse.bootstrapTrustedNode(RadixUniverse.LOCAL_SINGLE_NODE)` and that this is now an async function call. Waiting for bootstrap to complete will solve my issues with `identityManager.generateSimpleIdentity()`
