### ISSUE TITLE
Cannot read property 'getMagicByte' of undefined.

### ISSUE THREAD

**Issue by philcockfield** [radixdlt/radixdlt-js#15]
Running the following code with `1.0.5-alpha`:

```typescript
import { RadixAccount } from 'radixdlt';

const FAUCET = RadixAccount.fromAddress(
  '9ey8A461d9hLUVXh7CgbYhfmqFzjzSBKHvPC8SMjccRDbkTs2aM',
  true,
);
```

Produces the following error:

```
/PATH/node_modules/radixdlt/build/main/modules/universe/RadixUniverse.js:60
        return this.universeConfig.getMagicByte();
                                   ^

TypeError: Cannot read property 'getMagicByte' of undefined
    at RadixUniverse.getMagicByte (/PATH/node_modules/radixdlt/build/main/modules/universe/RadixUniverse.js:60:36)
    at Function.RadixKeyPair.fromAddress (/PATH/node_modules/radixdlt/build/main/modules/wallet/RadixKeyPair.js:22:22)
    at Function.RadixAccount.fromAddress (/PATH/node_modules/radixdlt/build/main/modules/account/RadixAccount.js:114:56)
    at Object.<anonymous> (/PATH/lib/example/TEMP.js:4:38)
```

----

This happens when the universe has not been bootstrapped.

```
radixUniverse.bootstrap(RadixUniverse.ALPHANET);
```

This feels like a common mistake people will make when picking up the API.  Wonder if you put a check in earlier in the pipeline with all methods that tell the dev to run `radixUniverse.bootstrap`.

**Comment by MuncleUscles** [comment]
Good idea, I could definitely warn people with a clear error

**Comment by Sajjon** [comment]
Closed since this library is now deprecated.
